name = "HEXA_TopOpt"
uuid = "a1b2c3d4-e5f6-4a5b-9c8d-7e6f5g4h3i2j"
authors = ["User"]
version = "1.0.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
AlgebraicMultigrid = "2169fc97-5a83-5252-b627-83903c6c433c"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
MarchingCubes = "299715c1-40a9-479a-aaf9-4a633d36f717"
MsgPack = "99f44e22-a591-53d1-9472-aa23ef4bd671"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
VortexLattice = "7a09bdf8-3785-11e9-0bdd-57d0ec69af3f"
WebSockets = "104b5d7c-a370-577a-8038-80a2059c5097"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1.9"
AbstractTrees = "=0.4.5"
AlgebraicMultigrid = "=1.1.0"
CSV = "=0.10.15"
CUDA = "=5.9.4"
DataFrames = "=1.8.1"
Dates = "=1.11.0"
FFTW = "=1.10.0"
FilePathsBase = "=0.9.24"
Gumbo = "=0.8.3"
HTTP = "=1.10.19"
ImageFiltering = "=0.7.12"
IterativeSolvers = "=0.9.4"
JSON = "=1.3.0"
Krylov = "=0.10.3"
LinearAlgebra = "=1.11.0"
LinearOperators = "=2.11.0"
MarchingCubes = "=0.1.11"
MsgPack = "=1.2.1"
OffsetArrays = "=1.17.0"
Plots = "=1.41.2"
Pluto = "=0.20.21"
PlutoUI = "=0.7.75"
Random = "=1.11.0"
SparseArrays = "=1.11.0"
StaticArrays = "=1.9.15"
Statistics = "=1.11.1"
URIs = "=1.6.1"
VortexLattice = "=0.2.3"
WebSockets = "=1.6.0"
YAML = "=0.4.16"
